name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:


        
  build:
  
    name: build app
    
    runs-on: ubuntu-latest
    
    env:
      app_name: latest_version.apk
      
    steps:
    
    - uses: actions/checkout@v3
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build debug APK
      run: bash ./gradlew assembleDebug --stacktrace
      
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Run AndroidLint with reviewdog
      uses: DVDAndroid/action-android-lint@v1.2
      with:
        github_token:
          ${{ secrets.GITHUB_TOKEN }}
        lint_xml_file:
          app/build/reports/lint-results.xml

    - name: Upload html test report
      uses: actions/upload-artifact@v2
      with:
        name: index.html
        path: app/build/reports/lint-results.xml
      
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
          name: app
          path: /home/runner/work/HSE2/HSE2/app/build/outputs/apk/debug/app-debug.apk
          
      
  lint:
  
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Run AndroidLint with reviewdog
        uses: DVDAndroid/action-android-lint@v1.2
        with:
          github_token:
            ${{ secrets.GITHUB_TOKEN }}
          lint_xml_file:
            app/build/reports/lint-results.xml
        
      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-results.xml
          
          
  send_version_to_telgram_bot:
  
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@master
    
    - uses: actions/download-artifact@v3
      with:
        name: app
        
    - name: ls 
      run: ls -la 
      
    - name: send message about new version
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_BOT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: app-debug.apk
