name: Unit testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew test

    - name: Upload html test report
      uses: actions/upload-artifact@v2
      with:
        name: index.html
        path: app/build/reports/tests/testDebugUnitTest/index.html

    - name: send message with report
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_BOT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: | 
          Testing report.
        document: app/build/reports/tests/testDebugUnitTest/index.html
